Mode = "debug"
ApiListen = ":8080"
DatabaseURL = "root:1234@tcp(localhost:3306)/titan_container?charset=utf8mb4&parseTime=True&loc=Local"
SecretKey = "test"

[ContainerManager]
   # Addr = "http://39.108.214.29:6123/rpc/v0"
    #Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.Dh8GU84xuJXwT-QikmKj7FBlKun7yVqvBhevJVoEP-o"
    Addr = "http://127.0.0.1:6123/rpc/v0"
    Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.p1OdEDVkui_qlzXTQfpXbWrTxzmUMtO0Yw5Revae2sA"
